#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ "$SHLVL" -eq 1 && ! -o LOGIN && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

export PATH=$HOME/.local/bin:$HOME/bin:$HOME/node_modules/.bin:/usr/local/heroku/bin:$PATH

export EDITOR="vim"

export HEROKU_SSL_VERIFY=disable
